[project]
id = "data-explorer"

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "http://localhost:8000"
additional_redirect_urls = ["http://localhost:3000", "http://localhost:5173"]

[auth.email]
enable_signup = true
enable_confirmations = false
